### PR TITLE
Updated node code for file upload service

### PR DESCRIPTION
**Pull request by Mritunjay10**
Here is an updated node.js code for multiple file upload service.

### CODE REVIEW

**Comment by gotev** [comment]
@Mritunjay10 first of all thanks for your PR! Got some time to review your code. Unfortunately, I can't merge this PR as it is now, because there are things which needs to be fixed, which I'll explain here.

If you simply clone your fork, go into the node.js server directory and perform `npm i` and then `npm start` you will get:

```
$ npm start

> node-js-test-mj@0.3.0 start /Users/alex/workspace/uploadservice-pr-mritunjay10/examples/server-nodejs
> node index.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'method-override'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/alex/workspace/uploadservice-pr-mritunjay10/examples/server-nodejs/index.js:8:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

because `method-override` library is missing in `package.json`.

A part this thing which is really trivial to solve, I've seen you basically just dropped all the existing implementations and made only what you needed to upload an image. The purpose of the demo server is:

* be able to debug requests and responses, 
* test basic authentication, 
* testing against an endpoint which responds with 401 
* testing binary and multipart uploads

so if this implementation you provided works for you I'm glad, but at this state it's not mergeable. 

What it's needed is only a refresh of dependencies and refactorings to make the server work with latest versions available.

Current node.js server available in upload service works well with node v10.15.0 and npm 6.4.1 without modifications, even if dependencies are really old.

At this point is up to you to decide if you want to make the needed modifications and go forward 🚀 please let me know. I'm available for guidance and for further code review 🙂

**Comment by Mritunjay10** [comment]
Thanks for the heads up I will fix that asap and let you know. I may need your guidance for 401 errors.

**Comment by gotev** [comment]
@Mritunjay10 I encourage you to start over with the actual node.js implementation and change only what is strongly needed for the server to work with newer dependecies versions.

**Comment by gotev** [comment]
Closing this because it's been idle for too long
