### ISSUE TITLE
Android 13 support Required

### ISSUE THREAD

**Issue by takmilul** [gotev/android-upload-service#631]
when i updated the sdk from 32 to 33, I am getting the below error while extending the PersistableData Class. System requires non-nullable parameter in writeToParcel method. if I try to override the method but is also conflicts.

Class 'UploadTaskParameters' is not abstract and does not implement abstract base class member public abstract fun writeToParcel(dest: Parcel, flags: Int): Unit defined in net.gotev.uploadservice.persistence.PersistableData

**Comment by gotev** [comment]
@takmilul what are you trying to accomplish?

**Comment by takmilul** [comment]
@gotev after updating the compile sdk to 33, i am getting the mentioned compile error. I need to run the project without any error. Please help me to solve the issue.
